src/todo/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'category', views.CategoryViewSet)

app_name = 'todo'
urlpatterns = [
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='category_detail'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:category_id>/save', views.store_post, name='store_post')
]

src/toko/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('todo/', include('todo.urls')),
    path('api/v1/product/', include('product.urls')),
    path('api/v1/order/', include('order.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('djoser.urls')),
    path('api/v1/', include('djoser.urls.authtoken')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/todo/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField(null=True)
    category_id = models.ForeignKey(Category, on_delete=models.SET_NULL, null= True)

    def __str__(self):
        return self.title

src/todo/views.py
from math import perm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from rest_framework import viewsets
from rest_framework import permissions

from todo.models import Category, Post
from todo.serializers import CategorySerializer, PostSerializer
class IndexView(generic.ListView):
    template_name = 'todo/index.html'

    def get_queryset(self):
        return Category.objects.all()

class DetailView(generic.DetailView):
    model = Category
    template_name = 'todo/detail.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'todo/post_detail.html'

def store_post(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    
    post = Post(category_id=category, title=request.POST['title'], body=request.POST['body'])
    post.save()

    return HttpResponseRedirect(reverse('todo:category_detail', args=(category_id,)))

class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class =  CategorySerializer
    permission_classes = [permissions.IsAuthenticated]

src/todo/templates/todo/detail.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ category }}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <h3>Deskripsi Kategori: {{ category.description }}</h3>

        <p>List post di kategori ini :</p>
        {% if category.post_set.count %}
            <ul>
                {% for post in category.post_set.all %}
                    <li>
                        <a href="{% url 'todo:post_detail' post.id %}">
                            {{ post }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Belum ada post</p>
        {% endif %}

        <form action="{% url 'todo:store_post' category.id %}" method="post">
            {% csrf_token %}

            <input type="text" name="title" id="">
            <textarea rows="" cols="" name="body"></textarea>

            <button type="submit">Save</button>
        </form>
    </body>
</html>

src/todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List Category</title>
</head>
<body>
    <ul>
        {% for cat in category_list %}
            <li>
                <a href="{% url 'todo:category_detail' cat.id %}">{{ cat }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

src/todo/templates/todo/post_detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ post }}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <h1>{{ post.title }}</h1>
        <p>{{ post.body }}</p>
    </body>
</html>